version: '3.8'

services:
  # Сервер (Backend)
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: dental-clinic-server-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=5000
      # Разрешаем CORS для всех источников
      - CORS_ORIGIN=*
    command: npm run dev
    networks:
      - dental-clinic-network

  # Клиент (Frontend) в режиме разработки
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: dental-clinic-client-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    command: npm start
    networks:
      - dental-clinic-network

# Сеть для контейнеров
networks:
  dental-clinic-network:
    driver: bridge 