version: '3.8'

services:
  # Сервер (Backend)
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: dental-clinic-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Разрешаем CORS для всех источников
      - CORS_ORIGIN=*
    networks:
      - dental-clinic-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Клиент (Frontend)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dental-clinic-client
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    networks:
      - dental-clinic-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

# Сеть для контейнеров
networks:
  dental-clinic-network:
    driver: bridge 